### ISSUE TITLE
🚸表单的问题

### ISSUE THREAD

**Issue by uni-zheng** [shirley5li/IFE-2018-CSS#2]
1. 先说 js 实现「当填入内容再删掉后，label还是上移缩小状态，不能恢复到最初输入框未填写的状态」，这个是因为你没有写 else 啊

```
// 邮箱输入框失去焦点时，根据输入框中是否内容设置label的样式
email_input.onblur = function() {
    var form_label_content = email_input.nextElementSibling.children[0];
    if (email_input.value) {   
        form_label_content.style.transform = 'translateY(-15px)';
        form_label_content.style.fontSize = '0.9em';
    } else {
        // reset
    }
};
```

2. 再说 css 实现，看看 :valid 这个伪类，搭配 input 的验证（html 中的表单校验）。
表单校验通过（有内容） => :valid 生效 
以后尽量不给你源码了 先自己想 有问题再问

**Comment by shirley5li** [comment]
再次谢谢哇，js的问题在你的帮助下解决了，但只利用html+css验证表单的时候，在输入框输入非空的非法值当输入框失去焦点时，label还会落下来，不知道现在这样不利用js可以实现即使是输入非法的非空值在失去焦点时，可以使label保持上移缩小状态么。

**Comment by uni-zheng** [comment]
我在测试的时候也发现 type=email 会有问题，css 没法判断 input 是否动态有值。只能把 type=email 改成 type=text 来处理。不过邮箱校验和动效肯定要取舍一下了。鉴于校验一般都走 js，所以我肯定舍弃 html 校验了。

**Comment by shirley5li** [comment]
好嗒，再次感谢解答，那就保留动画效果^^
