### ISSUE TITLE
🐛slider 的问题

### ISSUE THREAD

**Issue by uni-zheng** [shirley5li/IFE-2018-CSS#3]
没发现你通过 :target 实现中，translateY(350px) 导致的原因是什么。

但是这两个组合在一起才会出现问题。推测可能是浏览器 🐛 。

给你两个解决方法：
1. 移除 :target，通过 js 给 img 标签添加 class，通过 class 来启动动画。
2. 替换 img 上的 absolute，使用 fixed。

**Comment by shirley5li** [comment]
偷了个小懒，将img定位换成fixed解决了^-^

**Comment by uni-zheng** [comment]
😐
